laba
Paul-Vasylenko/web-lab5 pull request #1
Opened 2021-12-27 20:35 UTC by Paul-Vasylenko

2021-12-30 22:44 UTC, hxnchar requested changes

2021-12-30 22:44 UTC, hxnchar commented on src/todo.css
> +  border: 0 !important;
important вроде нехорошо юзать, я в интернетах читал...

2021-12-30 22:44 UTC, hxnchar commented on src/index.js
> +    audience={"https://dev--ani9se1.us.auth0.com/api/v2/"}
может audience в енв?

2021-12-30 22:44 UTC, hxnchar commented on src/index.js
> +  uri: "https://web-laba-5.herokuapp.com/v1/graphql",
может uri в енв?

2021-12-30 22:44 UTC, hxnchar commented on src/index.css
> +  background-color: #222 !important;
айайай, импортант...

2021-12-30 22:44 UTC, hxnchar commented on src/helpers/graphql-helper.js
> +    this.API_URL = "https://web-laba-5.herokuapp.com/v1/graphql";
this.API_URL в енв

2021-12-31 14:37 UTC, nosovk commented
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1398808/147828568-5cc2f5c8-7f54-4df5-beac-bc29d2cb05cf.png">

2022-01-02 18:10 UTC, nosovk commented on src/todo.css
> +  border: 0 !important;
ага, прийду я и скажу переписать :)

2022-01-02 18:10 UTC, nosovk commented on src/index.js
> +    audience={"https://dev--ani9se1.us.auth0.com/api/v2/"}
уже вроде переписали в env, но замечание верное

2022-01-02 18:11 UTC, nosovk commented
<img width="327" alt="image" src="https://user-images.githubusercontent.com/1398808/147885241-cc21a921-8180-4712-bb0b-8a2c7fe688f7.png">
а нам правда нужен этот permission?

2022-01-13 12:33 UTC, nosovk commented
<img width="858" alt="image" src="https://user-images.githubusercontent.com/1398808/149330938-590caf77-f510-4d7b-8844-61f18a48b90c.png">

2022-01-14 18:23 UTC, merged